rtx.skyBrightness = 1.0
rtx.bloom.burnIntensity = 1.4
rtx.bloom.luminanceThreshold = 0.65
rtx.pstrMaxBounces = 10

rtx.emissiveBlendOverrideEmissiveIntensity = 50

rtx.volumetrics.enable = True
#rtx.volumetrics.froxelGridResolutionScale = 16
#rtx.volumetrics.froxelDepthSlices = 48
rtx.volumetrics.maxAccumulationFrames = 24
rtx.volumetrics.froxelDepthSliceDistributionExponent = 2
rtx.volumetrics.froxelMaxDistanceMeters = 50

rtx.volumetrics.transmittanceColor = 0.930, 0.930, 0.930
rtx.volumetrics.transmittanceMeasurementDistanceMeters = 15.00
rtx.volumetrics.singleScatteringAlbedo = 0.950, 0.950, 0.950
rtx.volumetrics.anisotropy = -0.160
rtx.volumetrics.depthOffset = 1.00

rtx.volumetrics.enableFogRemap = False
rtx.volumetrics.fogRemapMaxDistanceMinMeters = 1
rtx.volumetrics.fogRemapMaxDistanceMaxMeters = 40
rtx.volumetrics.fogRemapTransmittanceMeasurementDistanceMinMeters = 20
rtx.volumetrics.fogRemapTransmittanceMeasurementDistanceMaxMeters = 100
rtx.volumetrics.fogRemapColorMultiscatteringScale = 0.1

rtx.volumetrics.enableAtmosphere = False
rtx.volumetrics.atmosphereInverted = False
rtx.volumetrics.atmosphereHeightMeters = 30

rtx.volumetrics.enableHeterogeneousFog = False
rtx.volumetrics.noiseFieldSubStepSizeMeters = 10
rtx.volumetrics.noiseFieldSpatialFrequency = 0.02
rtx.volumetrics.noiseFieldOctaves = 4
rtx.volumetrics.noiseFieldDensityScale = 0.07

rtx.dust.enable = False
rtx.dust.opacity = 0.05
rtx.dust.anisotropy = 0.5
rtx.dust.minParticleLife = 3
rtx.dust.minParticleSize = 1.5
rtx.dust.maxParticleSize = 5
rtx.dust.numberOfParticles = 1000000
rtx.dust.gravityForce = -0.5
rtx.dust.useTurbulence = True
rtx.dust.turbulenceAmplitude = 5
rtx.dust.turbulenceFrequency = 0.05
rtx.dust.minSpawnDistance = 150
rtx.dust.maxSpawnDistance = 1200
rtx.dust.maxSpeed = 3
rtx.dust.maxParticleLife = 5
rtx.dust.timeScale = 1
rtx.dust.rotationSpeed = 5